# fly.toml app configuration file generated for gpt-zoho-replier on 2024-07-14T11:12:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gpt-zoho-replier'
primary_region = 'sin'

[build]
  dockerfile = './Dockerfile'

[env]
  PORT = '8080'

[[mounts]]
  source = 'persist'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
